/* =========================================================
   Crete Family Holiday 2026
   File: js/data.js
   Purpose: central data source for itinerary, restaurants, beaches, budget and future maps
   ========================================================= */

window.creteTripData = {
    trip: {
        title: "Crete Family Holiday 2026",
        base: "Kamilari, South Crete",
        dates: "21 July – 6 August",
        family: "2 adults + children aged 12 and 15",
        budget: 2500,
        currency: "EUR"
    },
    itinerary: [
        {
                "day": 1,
                "title": "Arrival & Settle In",
                "date": "21 July",
                "theme": "Arrival",
                "tags": [
                        "Arrival",
                        "Groceries",
                        "Low activity"
                ],
                "morning": "Arrive at Heraklion Airport, collect the rental car and drive to Kamilari.",
                "lunch": "Flexible airport or road lunch depending on arrival time.",
                "afternoon": "Check in, unpack, buy water, breakfast items, fruit and snacks.",
                "evening": "Easy first evening in Kamilari or Pitsidia. No heavy planning.",
                "distanceKm": "65 km",
                "driveTime": "1h 05m",
                "activityCost": "€0",
                "foodBudget": "€60–90",
                "estimatedTotal": "€90–140 incl. groceries",
                "priceStatus": "Estimate",
                "priceSource": "Google Maps and grocery prices to verify",
                "color": "bg-warning",
                "text": ""
        },
        {
                "day": 2,
                "title": "Ancient Crete Day",
                "date": "22 July",
                "theme": "Archaeology",
                "tags": [
                        "Archaeology",
                        "Phaistos",
                        "Matala"
                ],
                "morning": "Phaistos Palace early before the heat. Optional quick stop near Agia Triada if timing works.",
                "lunch": "Lunch in Kamilari or a nearby village.",
                "afternoon": "Apartment and pool rest during peak heat.",
                "evening": "Matala stroll, caves viewpoint, sunset or simple dinner.",
                "distanceKm": "25–35 km",
                "driveTime": "35–50 min total",
                "activityCost": "Phaistos approx. €30 adults + kids likely free/reduced",
                "foodBudget": "€70–100",
                "estimatedTotal": "€100–140",
                "priceStatus": "Official price added",
                "priceSource": "Phaistos official full €15 / reduced €8",
                "color": "bg-info",
                "text": "text-white"
        },
        {
                "day": 3,
                "title": "Kommos & Kalamaki",
                "date": "23 July",
                "theme": "Beach & snorkeling",
                "tags": [
                        "Beach",
                        "Snorkeling",
                        "Low cost"
                ],
                "morning": "Beach and snorkeling time at Kommos or Kalamaki.",
                "lunch": "Simple beach lunch or taverna nearby.",
                "afternoon": "Apartment rest and shade.",
                "evening": "Sunset walk along Kalamaki or relaxed evening at apartment.",
                "distanceKm": "15–20 km",
                "driveTime": "25–35 min total",
                "activityCost": "€0 beach",
                "foodBudget": "€50–85",
                "estimatedTotal": "€55–95",
                "priceStatus": "Estimate",
                "priceSource": "Restaurant prices to verify",
                "color": "bg-primary",
                "text": "text-white"
        },
        {
                "day": 4,
                "title": "Agiofarago Adventure",
                "date": "24 July",
                "theme": "Nature",
                "tags": [
                        "Gorge",
                        "Beach",
                        "Nature"
                ],
                "morning": "Short gorge walk and beach visit. Start early and bring water, hats and snacks.",
                "lunch": "Picnic or nearby taverna depending on road conditions and timing.",
                "afternoon": "Apartment and pool recovery.",
                "evening": "Dinner in Pitsidia or Kamilari.",
                "distanceKm": "45–55 km",
                "driveTime": "1h 10m–1h 25m total",
                "activityCost": "€0",
                "foodBudget": "€45–90",
                "estimatedTotal": "€55–105",
                "priceStatus": "Estimate",
                "priceSource": "Road and parking check needed",
                "color": "bg-success",
                "text": "text-white"
        },
        {
                "day": 5,
                "title": "Zaros Lake & Mountain Villages",
                "date": "25 July",
                "theme": "Mountains & nature",
                "tags": [
                        "Nature",
                        "Lake",
                        "Village"
                ],
                "morning": "Zaros Lake / Votomos Lake area and a short nature walk.",
                "lunch": "Local lunch near Zaros, possibly trout or simple Cretan dishes.",
                "afternoon": "Apartment rest.",
                "evening": "Quiet Kamilari evening.",
                "distanceKm": "55–65 km",
                "driveTime": "1h 20m–1h 35m total",
                "activityCost": "€0",
                "foodBudget": "€60–95",
                "estimatedTotal": "€70–110",
                "priceStatus": "Estimate",
                "priceSource": "Restaurant prices to verify",
                "color": "bg-success",
                "text": "text-white"
        },
        {
                "day": 6,
                "title": "Matala & Red Beach",
                "date": "26 July",
                "theme": "Beach & village",
                "tags": [
                        "Beach",
                        "Matala",
                        "Sunset"
                ],
                "morning": "Morning beach in Matala area. Red Beach only if conditions and family energy are suitable.",
                "lunch": "Simple lunch in Matala or return near Kamilari.",
                "afternoon": "Apartment rest.",
                "evening": "Matala atmosphere, caves area viewpoint, ice cream or sunset.",
                "distanceKm": "22–30 km",
                "driveTime": "35–50 min total",
                "activityCost": "Matala Caves fee to verify",
                "foodBudget": "€65–100",
                "estimatedTotal": "€75–120",
                "priceStatus": "Fetch needed",
                "priceSource": "Matala cave fee to verify",
                "color": "bg-primary",
                "text": "text-white"
        },
        {
                "day": 7,
                "title": "Heraklion Museum Day",
                "date": "27 July",
                "theme": "Museum",
                "tags": [
                        "Museum",
                        "Heraklion",
                        "Culture"
                ],
                "morning": "Early visit to Heraklion Archaeological Museum.",
                "lunch": "Lunch in Heraklion, then return before evening traffic.",
                "afternoon": "Apartment rest after the city visit.",
                "evening": "Quiet evening at the apartment.",
                "distanceKm": "130–145 km",
                "driveTime": "2h 20m–2h 45m total",
                "activityCost": "Museum approx. €40 adults + kids free/reduced",
                "foodBudget": "€70–110",
                "estimatedTotal": "€120–170",
                "priceStatus": "Official price added",
                "priceSource": "Heraklion Museum official full €20",
                "color": "bg-secondary",
                "text": "text-white"
        },
        {
                "day": 8,
                "title": "Rest & Local Food Day",
                "date": "28 July",
                "theme": "Slow day",
                "tags": [
                        "Rest",
                        "Food",
                        "Groceries"
                ],
                "morning": "Pool/rest, bakery, local walk or very short outing.",
                "lunch": "Easy low-cost lunch at apartment or village.",
                "afternoon": "Rest and grocery refresh.",
                "evening": "Dinner in Kamilari or Pitsidia.",
                "distanceKm": "0–10 km",
                "driveTime": "0–15 min",
                "activityCost": "€0",
                "foodBudget": "€55–90",
                "estimatedTotal": "€60–100",
                "priceStatus": "Estimate",
                "priceSource": "Supermarket and restaurant prices to verify",
                "color": "bg-light",
                "text": ""
        },
        {
                "day": 9,
                "title": "Gortyna & Messara History",
                "date": "29 July",
                "theme": "History",
                "tags": [
                        "History",
                        "Gortyna",
                        "Museum"
                ],
                "morning": "Ancient Gortyna and Archaeological Museum of Messara if open and practical.",
                "lunch": "Nearby lunch or return towards Kamilari.",
                "afternoon": "Apartment rest.",
                "evening": "Quiet evening.",
                "distanceKm": "45–60 km",
                "driveTime": "1h 00m–1h 20m total",
                "activityCost": "Gortyna approx. €20 adults + kids likely free/reduced; Messara to verify",
                "foodBudget": "€60–95",
                "estimatedTotal": "€90–130",
                "priceStatus": "Partly official",
                "priceSource": "Gortyna official full €10 / reduced €5",
                "color": "bg-info",
                "text": "text-white"
        },
        {
                "day": 10,
                "title": "Agia Galini",
                "date": "30 July",
                "theme": "Coastal village",
                "tags": [
                        "Village",
                        "Beach",
                        "Lunch"
                ],
                "morning": "Harbour, beach time and coastal village walk.",
                "lunch": "Lunch in Agia Galini.",
                "afternoon": "Apartment rest.",
                "evening": "Sunset or relaxed local evening.",
                "distanceKm": "60–70 km",
                "driveTime": "1h 30m–1h 45m total",
                "activityCost": "€0",
                "foodBudget": "€70–110",
                "estimatedTotal": "€80–125",
                "priceStatus": "Estimate",
                "priceSource": "Restaurant prices to verify",
                "color": "bg-primary",
                "text": "text-white"
        },
        {
                "day": 11,
                "title": "Triopetra or Ligres",
                "date": "31 July",
                "theme": "Wild beach",
                "tags": [
                        "Beach",
                        "Scenic",
                        "Weather dependent"
                ],
                "morning": "Optional longer scenic beach day, only if wind, heat and energy are good.",
                "lunch": "Beach lunch or picnic.",
                "afternoon": "Return to apartment for rest.",
                "evening": "Quiet evening.",
                "distanceKm": "120–145 km",
                "driveTime": "2h 30m–3h total",
                "activityCost": "€0",
                "foodBudget": "€55–95",
                "estimatedTotal": "€75–120 incl. fuel",
                "priceStatus": "Estimate",
                "priceSource": "Weather and route check needed",
                "color": "bg-primary",
                "text": "text-white"
        },
        {
                "day": 12,
                "title": "Village & Market Day",
                "date": "1 August",
                "theme": "Local life",
                "tags": [
                        "Village",
                        "Market",
                        "Groceries"
                ],
                "morning": "Moires, local shopping, bakery, supermarket and easy village time.",
                "lunch": "Easy lunch.",
                "afternoon": "Apartment rest and grocery organization.",
                "evening": "Evening in Kamilari.",
                "distanceKm": "20–30 km",
                "driveTime": "30–45 min total",
                "activityCost": "€0",
                "foodBudget": "€60–110 incl. groceries",
                "estimatedTotal": "€70–125",
                "priceStatus": "Estimate",
                "priceSource": "Grocery prices to verify",
                "color": "bg-warning",
                "text": ""
        },
        {
                "day": 13,
                "title": "Snorkeling Repeat Favourite",
                "date": "2 August",
                "theme": "Flexible beach day",
                "tags": [
                        "Snorkeling",
                        "Beach",
                        "Flexible"
                ],
                "morning": "Repeat the best beach based on weather and what the family enjoyed most.",
                "lunch": "Simple lunch.",
                "afternoon": "Apartment rest.",
                "evening": "Relaxed evening.",
                "distanceKm": "15–40 km",
                "driveTime": "25–60 min total",
                "activityCost": "€0",
                "foodBudget": "€50–90",
                "estimatedTotal": "€60–105",
                "priceStatus": "Estimate",
                "priceSource": "Weather-dependent",
                "color": "bg-primary",
                "text": "text-white"
        },
        {
                "day": 14,
                "title": "Backup Adventure Day",
                "date": "3 August",
                "theme": "Plan B",
                "tags": [
                        "Flexible",
                        "Backup",
                        "Weather"
                ],
                "morning": "Reserved for weather backup, missed highlight or a low-energy day.",
                "lunch": "To decide.",
                "afternoon": "Flexible.",
                "evening": "Flexible evening.",
                "distanceKm": "0–70 km",
                "driveTime": "Flexible",
                "activityCost": "€0–40",
                "foodBudget": "€50–100",
                "estimatedTotal": "€60–150",
                "priceStatus": "Flexible",
                "priceSource": "Final decision during trip",
                "color": "bg-dark",
                "text": "text-white"
        },
        {
                "day": 15,
                "title": "Final Full Day",
                "date": "4 August",
                "theme": "Favourite day",
                "tags": [
                        "Favourite",
                        "Sunset",
                        "Special dinner"
                ],
                "morning": "Return to favourite beach or village.",
                "lunch": "Lunch at a favourite place.",
                "afternoon": "Apartment rest and begin packing.",
                "evening": "Final special dinner and sunset moment.",
                "distanceKm": "15–50 km",
                "driveTime": "30–75 min total",
                "activityCost": "€0",
                "foodBudget": "€100–150 special dinner",
                "estimatedTotal": "€110–170",
                "priceStatus": "Estimate",
                "priceSource": "Restaurant prices to verify",
                "color": "bg-danger",
                "text": "text-white"
        },
        {
                "day": 16,
                "title": "Departure Day",
                "date": "5/6 August",
                "theme": "Departure",
                "tags": [
                        "Departure",
                        "Airport",
                        "Packing"
                ],
                "morning": "Pack, check apartment, allow buffer time.",
                "lunch": "Simple meal depending on flight time.",
                "afternoon": "Drive to Heraklion Airport and return car.",
                "evening": "Departure.",
                "distanceKm": "65 km",
                "driveTime": "1h 05m",
                "activityCost": "€0",
                "foodBudget": "€30–60",
                "estimatedTotal": "€50–90 incl. fuel/snacks",
                "priceStatus": "Estimate",
                "priceSource": "Flight-time dependent",
                "color": "bg-secondary",
                "text": "text-white"
        }
],
    restaurants: [
        {
                "name": "Taverna Acropolis",
                "area": "Kamilari",
                "type": "Traditional",
                "budget": "budget",
                "cuisine": "Greek / Cretan",
                "image": "images/restaurants/taverna-acropolis.jpg",
                "distance": "Approx. 0–1 km",
                "drive": "Walk / 2–5 min",
                "familyCost": "€55–85",
                "reservation": "Recommended for dinner in high season",
                "highlights": "Traditional Greek dishes, village atmosphere, good low-drive option.",
                "vegetarian": "Some options likely; confirm on menu.",
                "bestFor": "Easy arrival evening, low-cost dinner, no driving.",
                "maps": "https://www.google.com/maps/search/?api=1&query=Taverna+Acropolis+Kamilari+Crete",
                "source": "Restaurant listing / to verify"
        },
        {
                "name": "Loggia",
                "area": "Kamilari",
                "type": "Seafood",
                "budget": "mid",
                "cuisine": "Seafood / Mediterranean",
                "image": "images/restaurants/loggia.jpg",
                "distance": "Approx. 0–1 km",
                "drive": "Walk / 2–5 min",
                "familyCost": "€80–120",
                "reservation": "Recommended",
                "highlights": "Seafood and Mediterranean food; useful for a nicer local dinner.",
                "vegetarian": "Some options likely; confirm on menu.",
                "bestFor": "One nicer dinner close to the apartment.",
                "maps": "https://www.google.com/maps/search/?api=1&query=Loggia+Kamilari+Crete",
                "source": "Restaurant listing / to verify"
        },
        {
                "name": "Taverna Kipos",
                "area": "Kamilari",
                "type": "Traditional",
                "budget": "mid",
                "cuisine": "Greek / European / daily specials",
                "image": "images/restaurants/taverna-kipos.jpg",
                "distance": "Approx. 1 km",
                "drive": "3–5 min",
                "familyCost": "€70–105",
                "reservation": "Recommended; website notes open every night except Mondays",
                "highlights": "Garden setting, family-run, home-cooked food, daily specials and vegetarian/seasonal dishes.",
                "vegetarian": "Yes, website mentions vegetarian and seasonal dishes.",
                "bestFor": "Relaxed garden meal, easy evening near Kamilari.",
                "maps": "https://www.google.com/maps/search/?api=1&query=Kipos+Restaurant+Kamilari+Crete",
                "source": "Official website / to verify before visit"
        },
        {
                "name": "Pizzeria Ariadni",
                "area": "Kamilari",
                "type": "Pizza",
                "budget": "mid",
                "cuisine": "Pizza / Italian",
                "image": "images/restaurants/pizzeria-ariadni.jpg",
                "distance": "Approx. 1 km",
                "drive": "3–5 min",
                "familyCost": "€60–90",
                "reservation": "Useful in high season",
                "highlights": "Good backup when the kids want pizza or pasta instead of another taverna meal.",
                "vegetarian": "Likely vegetarian pizza/pasta options.",
                "bestFor": "Easy family dinner and lower-risk food choice.",
                "maps": "https://www.google.com/maps/search/?api=1&query=Pizzeria+Ariadni+Kamilari+Crete",
                "source": "Restaurant listing / to verify"
        },
        {
                "name": "Taverna Babis",
                "area": "Pitsidia",
                "type": "Traditional",
                "budget": "budget",
                "cuisine": "Traditional Cretan / grilled dishes",
                "image": "images/restaurants/taverna-babis.jpg",
                "distance": "Approx. 5–7 km",
                "drive": "10–15 min",
                "familyCost": "€60–90",
                "reservation": "Recommended for dinner",
                "highlights": "Traditional Cretan cuisine, grill dishes, kokoretsi, Babis salad and Cretan hospitality.",
                "vegetarian": "Some Greek dishes likely; confirm.",
                "bestFor": "Traditional low-to-mid budget meal near Matala/Pitsidia.",
                "maps": "https://www.google.com/maps/search/?api=1&query=Taverna+Babis+Pitsidia+Crete",
                "source": "Official website / to verify before visit"
        },
        {
                "name": "SCALA Premium Sea Food Bar",
                "area": "Matala",
                "type": "Seafood",
                "budget": "special",
                "cuisine": "Seafood / Greek / European",
                "image": "images/restaurants/scala-matala.jpg",
                "distance": "Approx. 12–15 km",
                "drive": "15–20 min",
                "familyCost": "€120–170",
                "reservation": "Strongly recommended, especially for sunset/evening",
                "highlights": "Seafood-focused restaurant in Matala; good candidate for one memorable dinner.",
                "vegetarian": "Listings mention vegetarian/vegan/gluten-free options.",
                "bestFor": "Special seafood dinner or sunset meal in Matala.",
                "maps": "https://www.google.com/maps/search/?api=1&query=SCALA+Premium+Sea+Food+Bar+Matala",
                "source": "Restaurant listing / to verify"
        },
        {
                "name": "Agia Galini Harbour Tavernas",
                "area": "Agia Galini",
                "type": "Seafood",
                "budget": "mid",
                "cuisine": "Greek / seafood / harbour tavernas",
                "image": "images/restaurants/agia-galini-harbour.jpg",
                "distance": "Approx. 30–35 km each way",
                "drive": "45–55 min each way",
                "familyCost": "€80–120",
                "reservation": "Choose same day based on location/menu",
                "highlights": "Use as flexible harbour lunch/dinner rather than a fixed restaurant booking.",
                "vegetarian": "Depends on restaurant.",
                "bestFor": "Agia Galini day trip meal.",
                "maps": "https://www.google.com/maps/search/?api=1&query=Agia+Galini+restaurants+Crete",
                "source": "Planning placeholder"
        }
],
    beaches: [
        {
                "name": "Kommos Beach",
                "area": "Near Pitsidia / Matala",
                "image": "images/beaches/kommos.jpg",
                "driveCategory": "short",
                "snorkeling": "good",
                "facilitiesType": "basic",
                "distance": "Approx. 8–12 km",
                "drive": "10–15 min",
                "cost": "Free beach; umbrellas/food extra",
                "waterShoes": "Useful, especially near pebbly/rocky stretches",
                "shade": "Some natural shade/tamarisk areas; bring own shade",
                "facilities": "Basic/limited; organized section in the south; food and water nearby depending exact area",
                "wind": "Exposed to north-west/westerly winds; can become wavy quickly",
                "bestTime": "Morning or sunset",
                "familyFit": "Great low-cost beach day, but check waves before swimming.",
                "snorkelingNote": "Good around rocky/submerged areas on calm days.",
                "tip": "Avoid disturbing turtle nesting areas and avoid night beach visits in nesting season.",
                "maps": "https://www.google.com/maps/search/?api=1&query=Kommos+Beach+Crete"
        },
        {
                "name": "Kalamaki Beach",
                "area": "Kalamaki",
                "image": "images/beaches/kalamaki.jpg",
                "driveCategory": "short",
                "snorkeling": "okay",
                "facilitiesType": "organized",
                "distance": "Approx. 10–14 km",
                "drive": "15–20 min",
                "cost": "Free beach; food/umbrella costs extra",
                "waterShoes": "Optional",
                "shade": "Umbrellas/tavernas nearby; bring shade if staying longer",
                "facilities": "Village beach with tavernas and easier logistics",
                "wind": "Can be affected by same Messara Bay winds as Kommos",
                "bestTime": "Morning or evening",
                "familyFit": "Very easy family beach option close to Kamilari.",
                "snorkelingNote": "Better for swimming and relaxing than serious snorkeling.",
                "tip": "Good choice when you want simple dinner/sunset logistics.",
                "maps": "https://www.google.com/maps/search/?api=1&query=Kalamaki+Beach+Crete"
        },
        {
                "name": "Matala Beach",
                "area": "Matala",
                "image": "images/beaches/matala.jpg",
                "driveCategory": "short",
                "snorkeling": "okay",
                "facilitiesType": "organized",
                "distance": "Approx. 12–15 km",
                "drive": "15–20 min",
                "cost": "Free beach; cave visit/food/umbrellas extra",
                "waterShoes": "Useful but not mandatory",
                "shade": "Umbrellas/tavernas nearby; some shade depending timing",
                "facilities": "Tavernas, cafés, shops, sunbeds/umbrellas and parking nearby",
                "wind": "Bay can be calmer than open beaches but still check conditions",
                "bestTime": "Late afternoon / evening",
                "familyFit": "Good beach plus village atmosphere, but more crowded.",
                "snorkelingNote": "Interesting near rocks when calm; main draw is caves/village.",
                "tip": "Best as a mixed beach + dinner + sunset outing.",
                "maps": "https://www.google.com/maps/search/?api=1&query=Matala+Beach+Crete"
        },
        {
                "name": "Agiofarago Beach",
                "area": "Asterousia / Kaloi Limenes area",
                "image": "images/beaches/agiofarago.jpg",
                "driveCategory": "medium",
                "snorkeling": "good",
                "facilitiesType": "wild",
                "distance": "Approx. 45–55 km total day driving",
                "drive": "Drive + 25–50 min walk depending parking/route",
                "cost": "Free; possible parking/food truck costs if available",
                "waterShoes": "Recommended due to pebbles/rocks",
                "shade": "Very limited on the beach; gorge offers some shade earlier",
                "facilities": "Wild beach; no sunbeds; bring everything",
                "wind": "Often calmer than open beaches, but still weather-dependent",
                "bestTime": "Very early morning",
                "familyFit": "Adventure option for fit family, not a lazy logistics day.",
                "snorkelingNote": "Clear water and rock walls make it a strong snorkeling candidate on calm days.",
                "tip": "Bring proper shoes, water, hats and snacks; avoid midday heat.",
                "maps": "https://www.google.com/maps/search/?api=1&query=Agiofarago+Beach+Crete"
        },
        {
                "name": "Triopetra Beach",
                "area": "South Rethymno",
                "image": "images/beaches/triopetra.jpg",
                "driveCategory": "long",
                "snorkeling": "low",
                "facilitiesType": "organized",
                "distance": "Approx. 60–75 km each way",
                "drive": "1h 15m–1h 30m each way",
                "cost": "Free beach; food/fuel extra",
                "waterShoes": "Useful near rocks",
                "shade": "Sunbeds/tavernas in parts; bring backup shade",
                "facilities": "Tavernas, sunbeds/umbrellas and parking in parts",
                "wind": "Afternoon wind can create chop; mornings usually better",
                "bestTime": "Morning or late afternoon/sunset",
                "familyFit": "Beautiful but longer drive; use only as optional scenic day.",
                "snorkelingNote": "Swimming/scenery are stronger than snorkeling; rocky edges can be explored when calm.",
                "tip": "Choose only on a low-wind day and if everyone is ready for the drive.",
                "maps": "https://www.google.com/maps/search/?api=1&query=Triopetra+Beach+Crete"
        }
]
};
